# Generated by Django 5.2.3 on 2025-06-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jelovnik', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vrstajela',
            options={'ordering': ['redosled']},
        ),
        migrations.AddField(
            model_name='vrstajela',
            name='redosled',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
