# Generated by Django 5.2.3 on 2025-06-16 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Narudzba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('adresa', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=20)),
                ('napomena', models.TextField(blank=True, null=True)),
                ('kreirano', models.DateTimeField(auto_now_add=True)),
                ('zavrsena', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NarudzbaStavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jelo_id', models.IntegerField()),
                ('naziv', models.CharField(max_length=200)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=8)),
                ('kolicina', models.PositiveIntegerField(default=1)),
                ('narudzba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke', to='narudzbe.narudzba')),
            ],
        ),
    ]
